name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/Full-Stack-web-app-deployment-using-Java/fullstack-app
            git pull origin main
            npm install
            npm run build
            pm2 restart fullstack-app || pm2 start npm --name "fullstack-app" -- start
